library(ggplot2)
library(glmnet)
library(dplyr)
library(XML)
library(httr)
library(shiny)
library(car)
library(corrplot)
library(Rtsne)
library(caret)
library(xgboost)


sink("../../session-info.txt", append = TRUE)
cat("Session Information")
print(sessionInfo())
devtools::session_info()
sink()